package miaoshaproject.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.currennt_value
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    private Integer currenntValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.currennt_value
     *
     * @return the value of sequence_info.currennt_value
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    public Integer getCurrenntValue() {
        return currenntValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.currennt_value
     *
     * @param currenntValue the value for sequence_info.currennt_value
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    public void setCurrenntValue(Integer currenntValue) {
        this.currenntValue = currenntValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Sun Mar 29 20:17:55 CST 2020
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}